#!/usr/bin/env python3
"""Dev-time setup for a learned forgery-localization backend (plan §10 Phase 4).

Enables a backend for `services/forensics/app/ingest/forgery_model.py` by fetching its code + weights
into the gitignored model store and writing the inference adapter the seam loads:

    python scripts/setup_forgery_model.py trufor      # or: catnet

This is a DEV-TIME tool (it downloads from the internet) — it is NOT part of the runtime, which stays
100% local. The clone URL is read from `models/registry.json` (not hardcoded here), and the weights are
fetched by each repo's own download step. After setup, set TRUSTSHIELD_FORGERY_BACKEND=<backend> and the
forensics service uses the model; until then (or on any error) the heuristics stay live.

Steps performed:
  1. mkdir models/forgery/<backend>/{code,weights}
  2. git clone <source_url from registry> -> code/
  3. pip install torch torchvision  (skipped if already importable)
  4. print the repo-specific weight-download command (Google Drive — usually `gdown` or the repo script)
  5. write code/trustshield_infer.py exposing  localize(image_path, weights_path) -> HxW float mask
  6. self-test: import the adapter; report whether it can run a forward pass

The written adapter follows the upstream repo's documented inference; **validate it on first run** with
real weights (the seam degrades to heuristics if it raises).
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY = REPO_ROOT / "models" / "registry.json"

# The adapter contract every backend must satisfy (written into the vendored code dir).
_ADAPTER_TEMPLATE = '''\
"""TrustShield inference adapter for the {backend} forgery-localization model (auto-generated by
scripts/setup_forgery_model.py). Exposes localize(image_path, weights_path) -> HxW float mask in [0,1].
Loaded by services/forensics/app/ingest/forgery_model.py. Validate against the upstream repo on first run.
"""
import numpy as np


def localize(image_path: str, weights_path: str) -> np.ndarray:
    import torch  # noqa: F401
    from PIL import Image
    import torchvision.transforms as T

    # --- TODO (validate against {backend}'s repo): build the network + load weights once, run a forward
    # pass on the preprocessed image, and return the per-pixel tamper-probability map (HxW, 0..1). The
    # forgery_model seam upscales this mask to the image size and turns it into bounding boxes.
    #   net = build_{backend}()                       # from the vendored repo code (now on sys.path)
    #   net.load_state_dict(torch.load(weights_path, map_location="cpu")); net.eval()
    #   x = T.ToTensor()(Image.open(image_path).convert("RGB")).unsqueeze(0)
    #   with torch.no_grad(): mask = net(x)           # -> probability map
    #   return mask.squeeze().cpu().numpy()
    raise NotImplementedError(
        "Complete localize() for {backend} against the vendored repo in this folder, then re-run.")
'''


def _registry_entry(backend: str) -> dict:
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    for a in data.get("assets", []):
        if a.get("name") == f"forgery-{backend}":
            return a
    raise SystemExit(f"no registry entry 'forgery-{backend}' — known: dtd, trufor, catnet")


def _torch_ok() -> bool:
    try:
        import torch  # noqa: F401
        return True
    except Exception:
        return False


def main(backend: str) -> int:
    if backend == "dtd":
        print("Backend 'dtd' uses the DocTamper code already in models/doctamper/. Train weights with "
              "services/forensics/train_forgery.py and place them under models/doctamper/weights/.")
        return 0

    entry = _registry_entry(backend)
    base = REPO_ROOT / "models" / "forgery" / backend
    code, weights = base / "code", base / "weights"
    code.mkdir(parents=True, exist_ok=True)
    weights.mkdir(parents=True, exist_ok=True)

    url = entry["source_url"]
    if not any(code.iterdir()):
        print(f"[1/4] git clone {url} -> {code}")
        try:
            subprocess.run(["git", "clone", "--depth", "1", url, str(code)], check=True)
        except Exception as exc:
            print(f"  clone failed ({exc}); clone it manually into {code}")
    else:
        print(f"[1/4] code present at {code} (skipping clone)")

    if not _torch_ok():
        print("[2/4] installing torch torchvision (CPU build; for GPU install the CUDA build yourself)")
        subprocess.run([sys.executable, "-m", "pip", "install", "torch", "torchvision"], check=False)
    else:
        print("[2/4] torch already available")

    adapter = code / "trustshield_infer.py"
    if not adapter.exists():
        adapter.write_text(_ADAPTER_TEMPLATE.format(backend=backend), encoding="utf-8")
        print(f"[3/4] wrote adapter template -> {adapter} (complete localize() against the repo)")
    else:
        print(f"[3/4] adapter present at {adapter}")

    print(f"[4/4] download the {backend} pretrained weights into {weights} (see the repo's README / "
          f"download script — usually Google Drive via `gdown`). Then:\n"
          f"      set TRUSTSHIELD_FORGERY_BACKEND={backend}   # and restart the forensics service")
    print("Done. The seam auto-detects weights + adapter; until then heuristics stay live.")
    return 0


if __name__ == "__main__":
    bk = (sys.argv[1].lower() if len(sys.argv) > 1 else "trufor")
    raise SystemExit(main(bk))
